services:
  postgres:
    container_name: container_pg
    image: postgres
    hostname: localhost
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gowagr_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: container_pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    restart: unless-stopped

  cache:
    container_name: container_cache
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass gowagr
    volumes:
      - cache:/data

  # gowagr:
  #   build: .
  #   environment:
  #     NODE_ENV: PROD
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: root
  #     DB_DATABASE: gowagr_dev
  #     REDIS_HOST: cache
  #     REDIS_PORT: 6379
  #     REDIS_USERNAME: ''
  #     REDIS_PASS: gowagr
  #   depends_on:
  #     - postgres
  #     - cache
  #   ports:
  #     - '3000:3000'

volumes:
  postgres-data:
    driver: local
  cache:
    driver: local
